[project]
name = "nqs-nn-repr"
version = "0.1.0"
description = "project verifying the hypothesis of similar internal representations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.4.4",
    "scipy>=1.17.1",
    "torch>=2.11.0",
    "jax[cuda13]==0.7.2",
    "matplotlib>=3.10.8",
    "netket==3.21.0",
    "scienceplots>=2.2.1",
]

[project.scripts]
nqs-train = "nqs_universality.train:main"
nqs-plot = "nqs_universality.plot:main"

[tool.setuptools]
py-modules = ["nqs_universality"]

[tool.uv]
package = true