[tool.uv]
package = true

[project]
name = "nqs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jax[cuda]>=0.5.3",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "netket>=3.17.1",
]

[project.scripts]
tfim-train = "tfim_1d_nqs.train:main"
tfim-plot = "tfim_1d_nqs.plot:main"

[tool.setuptools]
py-modules = ["tfim_1d_nqs"]
